# Generated by Django 5.1.15 on 2026-09-10 16:58

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_account_email', models.EmailField(blank=True, max_length=254)),
                ('encrypted_refresh_token', apps.common.fields.EncryptedTextField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_workspace_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Workspace token',
            },
        ),
    ]
