# Generated by Django 5.1.15 on 2026-09-10 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('auth.login', 'User logged in'), ('auth.login_failed', 'Failed login attempt'), ('auth.logout', 'User logged out'), ('auth.register', 'Account created'), ('auth.password_change', 'Password changed'), ('account.role_change', 'Role changed'), ('prayer.view', 'Prayer request viewed'), ('prayer.create', 'Prayer request created'), ('prayer.update', 'Prayer request updated'), ('prayer.delete', 'Prayer request deleted'), ('prayer.vault_unlock', 'Prayer vault unlocked'), ('prayer.vault_unlock_failed', 'Prayer vault unlock failed'), ('integration.google_connect', 'Google Workspace connected'), ('integration.google_disconnect', 'Google Workspace disconnected'), ('record.create', 'Record created'), ('record.update', 'Record updated'), ('record.delete', 'Record deleted')], db_index=True, max_length=48)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
