# Generated by Django 5.1.15 on 2026-09-10 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('prayer_need', models.TextField()),
                ('category_sphere', models.CharField(choices=[('personal_growth', 'Personal Growth'), ('academia_career', 'Academia & Career'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('physical_wellbeing', 'Physical Wellbeing')], max_length=32)),
                ('privacy_level', models.CharField(choices=[('private_vault', 'Private vault (author only)'), ('mentor_only', 'Author + assigned mentor'), ('community_intercessors', 'Community intercessors')], default='private_vault', max_length=32)),
                ('is_answered', models.BooleanField(default=False)),
                ('praise_report', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PrayerIntercession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_intercessions', to=settings.AUTH_USER_MODEL)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercessions', to='prayers.prayerrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['privacy_level', '-created_at'], name='prayers_pra_privacy_568466_idx'),
        ),
        migrations.AddConstraint(
            model_name='prayerintercession',
            constraint=models.UniqueConstraint(fields=('prayer', 'user'), name='uniq_prayer_intercession'),
        ),
    ]
