# Generated by Django 5.1.15 on 2026-09-10 16:58

import apps.media.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('series', models.CharField(blank=True, max_length=150)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('speaker_role', models.CharField(blank=True, max_length=150)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=8)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=apps.media.models.episode_media_path)),
                ('video_embed_url', models.URLField(blank=True)),
                ('cover_image_theme', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('sphere', models.CharField(choices=[('personal_growth', 'Personal Growth'), ('academia_career', 'Academia & Career'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('physical_wellbeing', 'Physical Wellbeing')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('key_scriptures', models.JSONField(blank=True, default=list)),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-release_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EpisodeSave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_saves', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='media.podcastepisode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('episode', 'user'), name='uniq_episode_save')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_likes', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='media.podcastepisode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('episode', 'user'), name='uniq_episode_like')],
            },
        ),
    ]
