# Generated by Django 5.1.15 on 2026-09-10 16:58

import apps.resources.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('pdf_guide', 'PDF guide'), ('study_series', 'Study series'), ('sermon_transcript', 'Sermon transcript'), ('book_recommendation', 'Book recommendation')], max_length=32)),
                ('sphere', models.CharField(choices=[('personal_growth', 'Personal Growth'), ('academia_career', 'Academia & Career'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('physical_wellbeing', 'Physical Wellbeing')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('read_time', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.resources.models.resource_file_path)),
                ('external_url', models.URLField(blank=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('access_tier', models.CharField(choices=[('open_public', 'Open / public'), ('registered_disciples', 'Registered disciples'), ('elders_only', 'Elders only'), ('enrolled_cohort', 'Enrolled cohort')], default='open_public', max_length=32)),
                ('syllabus_chapters', models.JSONField(blank=True, default=list)),
                ('key_scripture_anchors', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource', 'user'), name='uniq_resource_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='ResourceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource', 'user'), name='uniq_resource_enrollment')],
            },
        ),
    ]
