# Generated by Django 5.1.15 on 2026-09-10 16:58

import apps.devotions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=150)),
                ('author_title', models.CharField(blank=True, max_length=150)),
                ('scripture_reference', models.CharField(blank=True, max_length=150)),
                ('scripture_text', models.TextField(blank=True)),
                ('reflection_body', models.TextField(blank=True)),
                ('prayer_point', models.TextField(blank=True)),
                ('practical_action_step', models.TextField(blank=True)),
                ('audio_voice_note', models.FileField(blank=True, null=True, upload_to=apps.devotions.models.devotion_audio_path)),
                ('audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('category_sphere', models.CharField(choices=[('personal_growth', 'Personal Growth'), ('academia_career', 'Academia & Career'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('physical_wellbeing', 'Physical Wellbeing')], max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=3)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DevotionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devotion_comments', to=settings.AUTH_USER_MODEL)),
                ('devotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devotions.devotion')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DevotionCommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='devotions.devotioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotion_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='uniq_devotion_comment_like')],
            },
        ),
        migrations.CreateModel(
            name='DevotionLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='devotions.devotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotion_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('devotion', 'user'), name='uniq_devotion_like')],
            },
        ),
    ]
