# Generated by Django 5.1.15 on 2026-09-11 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionReadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='devotions.devotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotion_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('devotion', 'user'), name='uniq_devotion_read')],
            },
        ),
    ]
