# Generated by Django 5.1.15 on 2026-09-10 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('sphere_focus', models.CharField(choices=[('personal_growth', 'Personal Growth'), ('academia_career', 'Academia & Career'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('physical_wellbeing', 'Physical Wellbeing')], max_length=32)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('scripture_text', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('in_app_video', 'In-app video'), ('in_app_audio', 'In-app audio'), ('audio_room', 'Audio room'), ('whatsapp', 'WhatsApp'), ('zoom', 'Zoom'), ('in_person', 'In person')], default='google_meet', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('meeting_notes', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('post_session_prayer', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=1024)),
                ('meet_space_id', models.CharField(blank=True, max_length=255)),
                ('meet_url', models.URLField(blank=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-scheduled_at',),
            },
        ),
    ]
